apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # For on-node storage (not for production)
    path: /data/mongodb
