apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Matches the labels in the deployment.yaml
  ports:
    - protocol: TCP
      port: 80              # Port for internal access in the cluster
      targetPort: 3001      # Port on the backend container
             # Port exposed externally
  type: ClusterIP          
