apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"  # Root username for MongoDB
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "Password"  # Root password for MongoDB
        - name: MONGO_INITDB_DATABASE
          value: "todos"  # Default database to create
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: ""  # No dynamic provisioning
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
